# config/_default/params.toml

defaultBackgroundImage = "/img/jwst_bg.jpg"
defaultAppearance = "dark"
colorScheme = "neon"
logo = "/img/cat.png"
highlightCurrentMenuArea = true
article.showHero = true


[header]
  layout = "fixed-fill" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "/img/iceland.jpg" # used in: hero, and card
  showRecent = false
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "docs"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background